import React, { useEffect, useState } from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowUpRight, BarChart3, Bell, Boxes, ChevronRight, CircleHelp, Cpu, Download, FileUp, LayoutDashboard, RefreshCw, Search, ShieldCheck, Users, Zap} from 'lucide-react';
import {BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Cell} from 'recharts';
import {api, Customer, percent} from './lib';
import './style.css';

type Comparison = {validation:Record<string,number>;test:Record<string,number>;training_seconds:number};
type Model = {selected:string;version:string;threshold:number;trained_at:string;comparison:Record<string,Comparison>;dataset:{splits:Record<string,{rows:number}>;churn_rate:number};regression:{mae:number;rmse:number;r2:number};selection_policy:string;training_seconds:number};
type Dashboard = {total_predictions:number;high_risk:number;average_probability:number|null;value_at_risk:number;recent:Customer[];distribution:{range:string;count:number}[]};
type Monitor = {status:string;rows:number;features:Record<string,{psi:number;missing_rate:number;out_of_range_rate:number;drift:boolean}>;performance:{status:string;rows:number;f1?:number;roc_auc?:number}};
type Explanation = {prediction:{churn_probability:number};base_probability:number;explanation:{feature:string;contribution:number;value:number}[];explanation_note:string};
const names:Record<string,string>={logistic:'Logistic regression',random_forest:'Random forest',xgboost:'XGBoost',pytorch:'PyTorch neural network'};
const nav = [{name:'Overview',icon:LayoutDashboard},{name:'Customers',icon:Users},{name:'Models',icon:Boxes},{name:'Monitoring',icon:Activity}];

function App(){
 const [page,setPage]=useState('Overview'); const [data,setData]=useState<Dashboard>(); const [model,setModel]=useState<Model>(); const [monitor,setMonitor]=useState<Monitor>(); const [rows,setRows]=useState<Customer[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [risk,setRisk]=useState(''); const [selected,setSelected]=useState<Customer>(); const [explanation,setExplanation]=useState<Explanation>(); const [explaining,setExplaining]=useState(false); const [toast,setToast]=useState('');
 async function refresh(){setLoading(true);setError('');try{const [d,m,c,o]=await Promise.all([api<Dashboard>('/dashboard'),api<Model>('/model/info'),api<Customer[]>('/customers?limit=500'),api<Monitor>('/monitoring')]);setData(d);setModel(m);setRows(c);setMonitor(o);}catch(e){setError(String(e));}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(id);}},[toast]);
 async function inspect(row:Customer){setSelected(row);setExplanation(undefined);setExplaining(true);try{setExplanation(await api<Explanation>('/explain',row.features));}catch(e){setError(String(e));}finally{setExplaining(false);}}
 async function upload(file?:File){if(!file)return;const body=new FormData();body.append('file',file);try{const response=await fetch('/api/predict/csv',{method:'POST',body,headers:sessionStorage.getItem('apiKey')?{'X-API-Key':sessionStorage.getItem('apiKey')!}:{}});if(!response.ok)throw new Error(await response.text());const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='signalforge-predictions.csv';a.click();URL.revokeObjectURL(url);setToast('Batch scored. Results downloaded.');await refresh();}catch(e){setError(String(e));}}
 const filtered=rows.filter(r=>r.customer_id.toLowerCase().includes(query.toLowerCase())&&(!risk||r.risk===risk));
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={()=>setPage('Overview')}><span className="brand-mark"><Zap size={21}/></span>SignalForge<span className="ai">AI</span></a><div className="workspace"><span className="workspace-avatar">S</span><div>Customer intelligence<small>Portfolio workspace</small></div><ChevronRight size={14}/></div><div className="nav-caption">WORKSPACE</div><nav>{nav.map(({name,icon:Icon})=><button key={name} onClick={()=>{setPage(name);setSelected(undefined);}} className={page===name?'active':''}><Icon size={18}/>{name}{name==='Monitoring'&&monitor?.status==='ALERT'&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="lifecycle"><div><span className="pulse"/> ML lifecycle active</div><p>From customer signals<br/>to explainable decisions.</p><div className="tiny-flow">INGEST <ChevronRight size={10}/> TRAIN <ChevronRight size={10}/> SERVE</div></div><a href="/api/docs" target="_blank"><CircleHelp size={16}/> API documentation <ArrowUpRight size={14}/></a><div className="profile"><span>SF</span><div>SignalForge demo<small>UCI research dataset</small></div></div></div></aside>
 <main><header className="topbar"><div>Workspace <ChevronRight size={13}/> <b>{page}</b></div><div className="top-actions"><span className="demo-badge">RESEARCH DEMO</span><button aria-label="Refresh data" onClick={()=>void refresh()}><RefreshCw size={17} className={loading?'spin':''}/></button><button aria-label="Set API key" onClick={()=>{const key=prompt('API key for this session (leave blank for local demo)');if(key!==null){sessionStorage.setItem('apiKey',key);void refresh();}}}><ShieldCheck size={17}/></button><Bell size={17}/></div></header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow">CUSTOMER INTELLIGENCE / {page.toUpperCase()}</div><h1>{selected?selected.customer_id:page==='Overview'?'See the signals. Act with clarity.':page==='Customers'?'Every customer has a signal.':page==='Models'?'Evidence before complexity.':'Confidence, continuously checked.'}</h1><p>{page==='Overview'?'An explainable view of churn risk, customer value, and model health.':page==='Customers'?'Explore scored customers and the factors behind each prediction.':page==='Models'?'Four model families. One reproducible evaluation protocol.':'Track distribution shifts, data quality, and delayed outcomes.'}</p></div><label className="primary-button"><FileUp size={16}/> Score a CSV<input type="file" accept=".csv" onChange={e=>void upload(e.target.files?.[0])}/></label></div>
 {error&&<div role="alert" className="error">{error}<button onClick={()=>void refresh()}>Retry</button></div>}
 {loading&&!data?<div className="empty">Loading live model and prediction data…</div>:!data||!model?<div className="empty">Start the API and train a model to connect this workspace.</div>:<>
 {selected?<><button className="text-button" onClick={()=>setSelected(undefined)}>← Back to customers</button><div className="detail-grid"><section className="card"><div className="section-label">CHURN PROBABILITY</div><div className="big-risk">{percent(selected.probability)}</div><span className={'badge '+selected.risk.toLowerCase()}>{selected.risk} RISK</span><p>Decision threshold: {percent(model.threshold)}</p><p>Value at risk: <b>{selected.value_at_risk.toFixed(1)}</b> index units</p><h3>Observed profile</h3>{Object.entries(selected.features).filter(([k])=>k!=='customer_id').map(([k,v])=><div className="profile-row" key={k}><span>{k.replaceAll('_',' ')}</span><b>{String(v??'Missing')}</b></div>)}</section><section className="card"><div className="card-title"><h2>What drives this prediction?</h2><span className="tag">SHAP</span></div><p className="muted">Contributions to calibrated churn probability</p>{explaining?<div className="empty">Computing model explanations…</div>:explanation&&<><div className="contributions">{explanation.explanation.map(e=><div className="contribution" key={e.feature}><span>{e.feature.replaceAll('_',' ')}</span><div><i style={{width:`${Math.min(100,Math.abs(e.contribution)*300)}%`,background:e.contribution>0?'#ed8a68':'#30aa94'}}/></div><b>{e.contribution>0?'+':''}{(e.contribution*100).toFixed(1)} pp</b></div>)}</div><div className="insight"><Zap size={18}/><div><b>Model-derived investigation signals</b><p>Inspect {explanation.explanation.filter(e=>e.contribution>0).slice(0,2).map(e=>e.feature.replaceAll('_',' ')).join(' and ')}. These associations do not establish causes or prove that an intervention will work.</p></div></div><p className="muted">Baseline: {percent(explanation.base_probability)}. {explanation.explanation_note}</p></>}<h3>Prediction history</h3>{rows.filter(r=>r.customer_id===selected.customer_id).map(r=><div className="profile-row" key={r.id}><span>{new Date(r.timestamp).toLocaleString()}</span><b>{percent(r.probability)}</b></div>)}</section></div></>:<>
 {page==='Overview'&&<><div className="status-strip"><span><span className="pulse"/> Serving {names[model.selected]}</span><span>Measured test PR-AUC <b>{model.comparison[model.selected].test.pr_auc.toFixed(3)}</b></span><span>Model {model.version}</span></div><div className="stats-grid"><Stat label="PREDICTIONS IN WINDOW" value={data.total_predictions.toLocaleString()} note="Latest 500 recorded predictions" icon={<Users size={18}/>}/><Stat label="HIGH-RISK PREDICTIONS" value={String(data.high_risk)} note={`${data.total_predictions?percent(data.high_risk/data.total_predictions):'0%'} of the current window`} icon={<Activity size={18}/>} tone="orange"/><Stat label="AVERAGE CHURN RISK" value={data.average_probability===null?'—':percent(data.average_probability)} note="Calibrated model probabilities" icon={<BarChart3 size={18}/>}/><Stat label="VALUE AT RISK INDEX" value={Math.round(data.value_at_risk).toLocaleString()} note="Estimated exposure · not currency" icon={<Zap size={18}/>}/></div><div className="overview-grid"><section className="card"><div className="card-title"><div><h2>Risk distribution</h2><p>Where predictions fall across the probability spectrum</p></div><span className="tag">LIVE WINDOW</span></div><ResponsiveContainer width="100%" height={255}><BarChart data={data.distribution} margin={{top:15,right:10,bottom:10,left:-25}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf1"/><XAxis dataKey="range" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip/><Bar isAnimationActive={false} dataKey="count" radius={[5,5,0,0]}>{data.distribution.map((_,i)=><Cell key={i} fill={i/10>=model.threshold?'#e5a07e':'#269d89'}/>)}</Bar></BarChart></ResponsiveContainer><div className="chart-foot"><span><i className="legend green"/> Lower risk</span><span><i className="legend orange"/> Above decision threshold</span></div></section><section className="card model-card"><div className="card-title"><h2>Production model</h2><Cpu size={20}/></div><div className="model-symbol"><Boxes size={28}/></div><h3>{names[model.selected]}</h3><p>Selected by validation average precision</p><div className="model-metrics"><div><b>{model.comparison[model.selected].test.roc_auc.toFixed(3)}</b><small>TEST ROC-AUC</small></div><div><b>{model.comparison[model.selected].test.f1.toFixed(3)}</b><small>TEST F1</small></div></div><button className="text-button" onClick={()=>setPage('Models')}>Explore evaluation <ArrowUpRight size={14}/></button></section></div><section className="card"><div className="card-title"><div><h2>Recent customer signals</h2><p>Actual API predictions from the research demo</p></div><button className="text-button" onClick={()=>setPage('Customers')}>View all customers <ArrowUpRight size={14}/></button></div><CustomerTable rows={data.recent} inspect={inspect}/></section></>}
 {page==='Customers'&&<section className="card"><div className="card-title"><h2>Customer explorer <span className="count">{filtered.length}</span></h2><div className="filters"><label className="search"><Search size={15}/><input aria-label="Search customer ID" placeholder="Search customer ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter risk" value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risk levels</option><option>HIGH</option><option>LOW</option></select></div></div><CustomerTable rows={filtered} inspect={inspect}/></section>}
 {page==='Models'&&<><div className="status-strip"><span><ShieldCheck size={16}/> {model.selection_policy}</span></div><section className="card"><div className="card-title"><div><h2>Model comparison</h2><p>Held-out test results · choice frozen using validation data</p></div><span className="tag">SEED 42</span></div><div className="table-scroll"><table><thead><tr><th>MODEL FAMILY</th><th>ROC-AUC</th><th>PR-AUC¹</th><th>PRECISION</th><th>RECALL</th><th>F1</th><th>TRAINING</th></tr></thead><tbody>{Object.entries(model.comparison).map(([name,r])=><tr key={name}><td><b>{names[name]}</b> {name===model.selected&&<span className="badge low">SERVING</span>}</td>{['roc_auc','pr_auc','precision','recall','f1'].map(k=><td key={k}>{r.test[k].toFixed(3)}</td>)}<td>{r.training_seconds.toFixed(1)}s</td></tr>)}</tbody></table></div><p className="muted">¹ Average precision. Training duration includes model search and calibration; machine-dependent.</p></section><div className="detail-grid"><section className="card"><h2>Evaluation protocol</h2><ol className="steps"><li>Group identical predictor profiles before splitting</li><li>Three-fold CV and two configurations per family</li><li>Fit sigmoid calibration on separate records</li><li>Select family and F1 threshold on validation data</li><li>Report untouched test performance</li></ol><p>{Object.entries(model.dataset.splits).map(([k,v])=>`${k}: ${v.rows}`).join(' · ')}</p></section><section className="card"><h2>Value-index regression</h2><p>Auxiliary random forest predicts the observed calculated customer-value index. This is not a forecast of future revenue.</p><div className="model-metrics"><div><b>{model.regression.mae.toFixed(2)}</b><small>MAE</small></div><div><b>{model.regression.r2.toFixed(3)}</b><small>R²</small></div></div><p className="muted">Exposure = churn probability × predicted value index. No currency or causal interpretation.</p></section></div></>}
 {page==='Monitoring'&&monitor&&<><div className="stats-grid"><Stat label="REFERENCE COMPARISON" value={monitor.status} note="PSI threshold: 0.20" icon={<Activity/>}/><Stat label="OBSERVED WINDOW" value={String(monitor.rows)} note="Current model · latest 500" icon={<Users/>}/><Stat label="DRIFTED FEATURES" value={String(Object.values(monitor.features).filter(f=>f.drift).length)} note="Heuristic alerts require investigation" icon={<BarChart3/>}/><Stat label="LABELED OUTCOMES" value={String(monitor.performance.rows)} note={monitor.performance.status} icon={<ShieldCheck/>}/></div><section className="card"><div className="card-title"><div><h2>Feature distribution health</h2><p>Compared with the training reference; drift does not prove performance loss.</p></div><button className="text-button" onClick={async()=>{try{await api('/monitoring/run',{});setToast('Monitoring snapshot saved.');}catch(e){setError(String(e));}}}>Save snapshot <Download size={14}/></button></div><table><thead><tr><th>FEATURE</th><th>PSI</th><th>MISSING</th><th>OUTSIDE TRAIN RANGE</th><th>STATUS</th></tr></thead><tbody>{Object.entries(monitor.features).map(([name,f])=><tr key={name}><td>{name.replaceAll('_',' ')}</td><td>{f.psi.toFixed(3)}</td><td>{percent(f.missing_rate)}</td><td>{percent(f.out_of_range_rate)}</td><td><span className={'badge '+(f.drift?'high':'low')}>{f.drift?'INVESTIGATE':'STABLE'}</span></td></tr>)}</tbody></table>{monitor.rows===0&&<div className="empty">Score customers to begin monitoring.</div>}</section><div className="insight"><ShieldCheck/><div><b>Promotion is gated by evidence</b><p>Drift can trigger candidate training. Promotion requires independent labels, improved average precision, and calibration and recall guardrails. Missing labels never become invented performance scores.</p></div></div></>}
 </>}</>}
 <footer><span>SignalForge AI <span className="muted">/ Explainable customer intelligence</span></span><span>UCI Iranian Churn · CC BY 4.0 · Research demo</span></footer></div></main>{toast&&<div role="status" className="toast">{toast}</div>}</div>
}
function Stat({label,value,note,icon,tone=''}:{label:string;value:string;note:string;icon:React.ReactNode;tone?:string}){return <section className={'stat '+tone}><div className="stat-top"><span>{label}</span>{icon}</div><strong>{value}</strong><p>{note}</p></section>}
function CustomerTable({rows,inspect}:{rows:Customer[];inspect:(r:Customer)=>void}){return <div className="table-scroll"><table><thead><tr><th>CUSTOMER</th><th>CHURN PROBABILITY</th><th>RISK LEVEL</th><th>VALUE AT RISK</th><th>SCORED</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><button className="customer-link" onClick={()=>inspect(r)}><span className="customer-avatar">{r.customer_id.slice(-2)}</span>{r.customer_id}</button></td><td><div className="risk-cell"><span>{percent(r.probability)}</span><div className="mini-bar"><i style={{width:percent(r.probability),background:r.risk==='HIGH'?'#df956d':'#29a68d'}}/></div></div></td><td><span className={'badge '+r.risk.toLowerCase()}><i/>{r.risk}</span></td><td>{r.value_at_risk.toFixed(1)} <small>index</small></td><td className="muted">{new Date(r.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td><td><button aria-label={`Inspect ${r.customer_id}`} className="icon-button" onClick={()=>inspect(r)}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No predictions match. Upload a customer CSV to get started.</div>}</div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
